version: '3.8'

services:
  postgres:
    container_name: postgres_erazor
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env

  redis:
    container_name: redis_erazor
    image: redis/redis-stack:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: